# The directory containing the pdfs to convert
pdf_dir: <PROJECT_PATH>/input/small-pdf-dataset

# The directory to place the converted pdfs in
out_dir: <PROJECT_PATH>/output/pypdf

# The settings for the pdf parser
parser_settings:
  # The name of the parser to use
  name: pypdf

# The compute settings for the workflow
compute_settings:
  # The name of the compute platform to use
  name: <COMPUTE_NAME>
  # The number of compute nodes to use
  num_nodes: 1
  # Path to conda environment
  worker_init: "<WORKER_INIT>"
  # The scheduler options to use when submitting jobs
  scheduler_options: "<SCHEDULER_OPTIONS>"
  # Make sure to change the account to the account you want to charge
  account: <PROJECT_NAME>
  # The HPC queue to submit to
  queue: debug
  # The amount of time to request for your job
  walltime: 00:15:00
